# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bbad44303f1c5227a422c9e5fafdf4f7"
name = "basic-task"
handle = "basic-task"
application_url = "https://wherever-die-bed-friendly.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://wherever-die-bed-friendly.trycloudflare.com/auth/callback", "https://wherever-die-bed-friendly.trycloudflare.com/auth/shopify/callback", "https://wherever-die-bed-friendly.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
